# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncKqdJkuK0fzBiDFiAhxh0Y_q3Aqi2b2
"""

import collections

goodies = {"Fitbit Plus" : 7980,
"IPods": 22349,
"MI Band": 999,
"Cult Pass": 2799,
"Macbook Pro": 229900,
"Digital Camera": 11101,
"Alexa": 9999,
"Sandwich Toaster": 2195,
"Microwave Oven": 9800,
"Scale": 4999 }


a = sorted(goodies.items(), key=lambda x: x[1])    
goodies_len = len(a)

employee = input("Enter number of employee: ")
employee = int(employee)
if ((employee > goodies_len) or (employee < 0)):
    print ("Not possibel to distribute")
    exit(0)

min_index1 = 0;
min_index2 = 0;
diff = (a[goodies_len-1][1] - a[0][1]) + 1;

for i in range(0,len(a)-employee+1): 
    diff_curr = abs(a[i][1] - a[i+employee-1][1]);
    if (diff_curr < diff):
        min_index1 = i
        min_index2 = i+employee-1;
        diff = diff_curr

for i in range(min_index1, min_index2+1):
    print(str(a[i][0]) + " : "+str(a[i][1]))